service: elm-serverless-demo

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    location: .webpack

functions:
  api:
    handler: api.handler # Refers to function `handler` exported from `api.js`
    events:
      # The following sets up Lambda Proxy Integration
      # Basically, the elm app will do the routing instead of
      # API Gateway
      - http:
          integration: lambda-proxy
          path: /
          method: ANY
      - http:
          integration: lambda-proxy
          path: /{proxy+}
          method: ANY
